blank_issues_enabled: false

contact_links:
  - name: WeDot 提案
    url: https://github.com/Wedot-Engine/To-Do
    about: 请在 To-Do 仓库提交您想要的功能提案。

  - name: WeDot 文档仓库
    url: https://github.com/Wedot-Engine/WeDot-docs
    about: 请在 WeDot 文档仓库提交文档相关的问题和错误。

  - name: WeDot 社区
    url: https://wedot.top/community
    about: 请在 WeDot 社区咨询技术支持。
