name: '保存 WeDot 的编译缓存'
description: '保存 WeDot 的编译缓存。'
inputs:
  cache-name:
    description: '缓存名称（默认为 job 名称，就是 jobs: 的子）。'
    default: ${{ github.job }}
  scons-cache:
    description: 'SCons 缓存路径。'
    default: ${{ github.workspace }}/.scons-cache/

runs:
  using: composite
  steps:
    - name: 缓存 SCons 的缓存目录
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.scons-cache }}
        key: ${{ inputs.cache-name }}-${{ env.GODOT_BASE_BRANCH }}-${{ github.ref }}-${{ github.sha }}
