name: 测试 WeDot 项目
description: 测试 WeDot 项目的打开和运行。

inputs:
  bin:
    description: WeDot 可执行文件的路径。
    required: true

runs:
  using: composite
  steps:
    # 下载并解压项目。重命名项目文件夹可以简化后期替换测试项目的流程
    # 目前仍使用 Godot 的测试项目
    - name: 部署项目
      shell: sh
      run: |
        wget https://github.com/godotengine/regression-test-project/archive/4.0.zip
        unzip 4.0.zip
        mv "regression-test-project-4.0" "test_project"

    # 测试编辑器

    - name: Vulkan 下启动关闭编辑器
      shell: sh
      run: |
        xvfb-run ${{ inputs.bin }} --audio-driver Dummy --editor --quit --path test_project 2>&1 | tee sanitizers_log.txt || true
        misc/scripts/check_ci_log.py sanitizers_log.txt

    - name: GLES3 下启动关闭编辑器
      shell: sh
      run: |
        DRI_PRIME=0 xvfb-run ${{ inputs.bin }} --audio-driver Dummy --rendering-driver opengl3 --editor --quit --path test_project 2>&1 | tee sanitizers_log.txt || true
        misc/scripts/check_ci_log.py sanitizers_log.txt

    # 运行测试项目
    - name: 运行项目
      shell: sh
      run: |
        xvfb-run ${{ inputs.bin }} 40 --audio-driver Dummy --path test_project 2>&1 | tee sanitizers_log.txt || true
        misc/scripts/check_ci_log.py sanitizers_log.txt
