name: 上传 WeDot 产物
description: 上传 WeDot 产物。

inputs:
  name:
    description: 产物名称。
    default: ${{ github.job }}
  path:
    description: 上传路径
    required: true
    default: bin/*

runs:
  using: composite
  steps:
    - name: 上传 WeDot 产物
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        # 默认 90 日。
        retention-days: 60
