name: 🍏 iOS 编译测试
on:
  workflow_call:

# 全局设置
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: main
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes strict_checks=yes

concurrency:
  group: ci-${{ github.actor }}-${{ github.head_ref || github.run_number }}-${{ github.ref }}-ios
  cancel-in-progress: true

jobs:
  ios-template:
    runs-on: macos-latest
    name: Template (target=template_release)

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: ios
          target: template_release
          tests: false

      - name: 保存 WeDot 编译缓存
        uses: ./.github/actions/wedot-cache-save
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
